//! Non-destructive bounded diagnostic inspection for RockStream nodes and environments.

use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};

use crate::output::{render_output, Formattable, OutputFormat};
use crate::CliError;
use rockstream_types::candidate_identity::CandidateIdentity;
use rockstream_types::config_resolver::{CliConfigOverrides, ConfigResolver};
use rockstream_types::config_validation::validate_config_str;
use rockstream_types::error_code::{RS_0003, RS_3025, RS_3026, RS_3027, RS_3028};
use rockstream_types::platform::{ClassificationTier, PlatformClassifier};

/// Upper bound on the number of diagnostic checks executed in a single run.
pub const MAX_DOCTOR_CHECKS: usize = 64;

/// Default per-check execution timeout.
pub const DEFAULT_CHECK_TIMEOUT: Duration = Duration::from_secs(5);

/// Hard upper bound on overall diagnostic runtime.
pub const MAX_DOCTOR_TIMEOUT: Duration = Duration::from_secs(30);

/// Status of an individual diagnostic check or the overall report.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DiagnosticStatus {
    Pass,
    Warn,
    Fail,
    Skip,
}

impl std::fmt::Display for DiagnosticStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Pass => write!(f, "PASS"),
            Self::Warn => write!(f, "WARN"),
            Self::Fail => write!(f, "FAIL"),
            Self::Skip => write!(f, "SKIP"),
        }
    }
}

/// Result of a single diagnostic check.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DiagnosticCheckResult {
    pub id: String,
    pub category: String,
    pub status: DiagnosticStatus,
    pub summary: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_steps: Option<String>,
    pub duration_ms: u64,
}

/// Comprehensive report generated by `rockstream doctor`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DoctorReport {
    pub status: DiagnosticStatus,
    pub checks: Vec<DiagnosticCheckResult>,
    pub passed_count: usize,
    pub warn_count: usize,
    pub failed_count: usize,
    pub skipped_count: usize,
    pub total_duration_ms: u64,
}

impl Formattable for DoctorReport {
    fn to_text(&self) -> String {
        let mut lines = Vec::new();
        lines.push(format!(
            "Doctor Diagnostics: {} ({} passed, {} warnings, {} failed, {} skipped) in {}ms",
            self.status,
            self.passed_count,
            self.warn_count,
            self.failed_count,
            self.skipped_count,
            self.total_duration_ms
        ));
        lines.push(format!(
            "{:<8} {:<12} {:<36} {}",
            "STATUS", "CATEGORY", "CHECK ID", "SUMMARY"
        ));
        lines.push("-".repeat(90));

        for check in &self.checks {
            lines.push(format!(
                "[{:<4}] {:<12} {:<36} {} ({}ms)",
                check.status, check.category, check.id, check.summary, check.duration_ms
            ));
            if let Some(ref details) = check.details {
                lines.push(format!("         Details:    {}", details));
            }
            if let Some(ref code) = check.code {
                lines.push(format!("         Error Code: {}", code));
            }
            if let Some(ref steps) = check.next_steps {
                lines.push(format!("         Next Steps: {}", steps));
            }
        }

        lines.join("\n")
    }
}

/// Execution options for `rockstream doctor`.
#[derive(Debug, Clone)]
pub struct DoctorOptions {
    pub config_path: Option<PathBuf>,
    pub storage: Option<String>,
    pub control: Option<String>,
    pub gateway: Option<String>,
    pub deep: bool,
    pub include_docker: bool,
    pub timeout: Duration,
    pub tls_cert_path: Option<PathBuf>,
    pub tls_key_path: Option<PathBuf>,
    pub tls_ca_cert_path: Option<PathBuf>,
    pub internal_tls_cert_path: Option<PathBuf>,
    pub internal_tls_key_path: Option<PathBuf>,
    pub internal_tls_ca_cert_path: Option<PathBuf>,
}

impl Default for DoctorOptions {
    fn default() -> Self {
        Self {
            config_path: None,
            storage: None,
            control: None,
            gateway: None,
            deep: false,
            include_docker: false,
            timeout: DEFAULT_CHECK_TIMEOUT,
            tls_cert_path: None,
            tls_key_path: None,
            tls_ca_cert_path: None,
            internal_tls_cert_path: None,
            internal_tls_key_path: None,
            internal_tls_ca_cert_path: None,
        }
    }
}

/// Redact sensitive values (passwords, tokens, keys) from a string.
pub fn redact_secrets(input: &str) -> String {
    rockstream_types::diagnostic::redact_secrets(input)
}

/// Execute all diagnostic checks and construct a `DoctorReport`.
pub async fn run_doctor_checks(opts: &DoctorOptions) -> DoctorReport {
    let start_all = Instant::now();
    let mut checks = Vec::with_capacity(MAX_DOCTOR_CHECKS);
    let check_timeout = opts.timeout.min(MAX_DOCTOR_TIMEOUT);

    // 1. Binary Candidate Identity
    checks.push(
        run_bounded_check(
            "binary.candidate_identity",
            "binary",
            check_timeout,
            || async {
                let id = CandidateIdentity::current();
                if id.semantic_version.is_empty() || id.commit_sha.is_empty() {
                    (
                        DiagnosticStatus::Fail,
                        "Candidate identity has missing version or commit SHA".to_string(),
                        None,
                        Some("RS-0001".to_string()),
                        Some(
                            "Verify the binary was built with standard build metadata.".to_string(),
                        ),
                    )
                } else {
                    (
                        DiagnosticStatus::Pass,
                        format!(
                            "Version {} (sha: {}, features: {:?})",
                            id.semantic_version, id.commit_sha, id.enabled_features
                        ),
                        None,
                        None,
                        None,
                    )
                }
            },
        )
        .await,
    );

    // 2. Config Parse & Semantic Validation
    checks.push(run_bounded_check("config.parse_and_semantic", "config", check_timeout, || async {
        let overrides = CliConfigOverrides::default();
        match ConfigResolver::resolve(opts.config_path.as_deref(), &overrides) {
            Ok(resolved) => {
                let toml_str = resolved.config.to_string().unwrap_or_default();
                let report = validate_config_str(&toml_str, false);
                if !report.valid {
                    let errs = report.diagnostics.iter().map(|d| d.message.clone()).collect::<Vec<_>>().join("; ");
                    (
                        DiagnosticStatus::Fail,
                        "Configuration contains semantic validation errors".to_string(),
                        Some(redact_secrets(&errs)),
                        Some("RS-0002".to_string()),
                        Some("Fix configuration errors reported by `rockstream config validate`.".to_string()),
                    )
                } else if !report.diagnostics.is_empty() {
                    let warns = report.diagnostics.iter().map(|d| d.message.clone()).collect::<Vec<_>>().join("; ");
                    (
                        DiagnosticStatus::Warn,
                        "Configuration valid with warnings".to_string(),
                        Some(redact_secrets(&warns)),
                        None,
                        None,
                    )
                } else {
                    (
                        DiagnosticStatus::Pass,
                        "Configuration is valid and within semantic bounds".to_string(),
                        None,
                        None,
                        None,
                    )
                }
            }
            Err(e) => (
                DiagnosticStatus::Fail,
                format!("Configuration resolution failed: {e}"),
                None,
                Some("RS-0002".to_string()),
                Some("Check configuration file syntax and environment variables.".to_string()),
            ),
        }
    }).await);

    // 3. System Monotonic Clock
    checks.push(
        run_bounded_check(
            "system.monotonic_clock",
            "system",
            check_timeout,
            || async {
                let t1 = Instant::now();
                tokio::time::sleep(Duration::from_millis(2)).await;
                let t2 = Instant::now();
                if t2 > t1 {
                    (
                        DiagnosticStatus::Pass,
                        "System monotonic clock is advancing strictly monotonically".to_string(),
                        None,
                        None,
                        None,
                    )
                } else {
                    (
                        DiagnosticStatus::Fail,
                        "System monotonic clock did not advance forward".to_string(),
                        None,
                        Some("RS-0003".to_string()),
                        Some("Verify host timekeeping and monotonic timer stability.".to_string()),
                    )
                }
            },
        )
        .await,
    );

    // 4. System Temp Directory
    checks.push(
        run_bounded_check("system.temp_directory", "system", check_timeout, || async {
            match tempfile::tempdir() {
                Ok(dir) => {
                    let test_file = dir.path().join("doctor_test.tmp");
                    if let Err(e) = std::fs::write(&test_file, b"probe") {
                        return (
                            DiagnosticStatus::Fail,
                            format!("Failed to write to temp directory: {e}"),
                            None,
                            Some("RS-0003".to_string()),
                            Some(
                                "Check system /tmp directory permissions and free space."
                                    .to_string(),
                            ),
                        );
                    }
                    if let Err(e) = std::fs::read(&test_file) {
                        return (
                            DiagnosticStatus::Fail,
                            format!("Failed to read from temp directory: {e}"),
                            None,
                            Some("RS-0003".to_string()),
                            Some("Check system /tmp directory permissions.".to_string()),
                        );
                    }
                    let _ = std::fs::remove_file(&test_file);
                    (
                        DiagnosticStatus::Pass,
                        format!(
                            "System temp directory is writable and readable ({})",
                            dir.path().display()
                        ),
                        None,
                        None,
                        None,
                    )
                }
                Err(e) => (
                    DiagnosticStatus::Fail,
                    format!("Failed to create temporary directory: {e}"),
                    None,
                    Some("RS-0003".to_string()),
                    Some("Check TMPDIR environment variable and permissions.".to_string()),
                ),
            }
        })
        .await,
    );

    // 5. System File Descriptor Limit
    checks.push(
        run_bounded_check(
            "system.file_descriptor_limit",
            "system",
            check_timeout,
            || async {
                #[cfg(unix)]
                {
                    let mut rlim = sys_ffi::rlimit {
                        rlim_cur: 0,
                        rlim_max: 0,
                    };
                    let res = unsafe { sys_ffi::getrlimit(sys_ffi::RLIMIT_NOFILE, &mut rlim) };
                    if res == 0 {
                        let cur = rlim.rlim_cur;
                        if cur >= 1024 {
                            (
                                DiagnosticStatus::Pass,
                                format!(
                                    "File descriptor limit is sufficient (soft limit: {})",
                                    cur
                                ),
                                None,
                                None,
                                None,
                            )
                        } else {
                            (
                                DiagnosticStatus::Warn,
                                format!("File descriptor soft limit is low ({} < 1024)", cur),
                                None,
                                Some("RS-0002".to_string()),
                                Some(
                                    "Increase file descriptor limit via `ulimit -n 65536`."
                                        .to_string(),
                                ),
                            )
                        }
                    } else {
                        (
                            DiagnosticStatus::Warn,
                            "Unable to query file descriptor limit via getrlimit".to_string(),
                            None,
                            None,
                            None,
                        )
                    }
                }
                #[cfg(not(unix))]
                {
                    (
                        DiagnosticStatus::Pass,
                        "File descriptor limit check not applicable on non-Unix platforms"
                            .to_string(),
                        None,
                        None,
                        None,
                    )
                }
            },
        )
        .await,
    );

    // 6. System Memory Available
    checks.push(
        run_bounded_check(
            "system.memory_available",
            "system",
            check_timeout,
            || async {
                #[cfg(unix)]
                {
                    let pages = unsafe { sys_ffi::sysconf(sys_ffi::_SC_PHYS_PAGES) };
                    let page_size = unsafe { sys_ffi::sysconf(sys_ffi::_SC_PAGE_SIZE) };
                    if pages > 0 && page_size > 0 {
                        let total_mem_mb = (pages as u64 * page_size as u64) / (1024 * 1024);
                        if total_mem_mb >= 512 {
                            (
                                DiagnosticStatus::Pass,
                                format!(
                                    "Host memory is sufficient (total physical: {} MB)",
                                    total_mem_mb
                                ),
                                None,
                                None,
                                None,
                            )
                        } else {
                            (
                                DiagnosticStatus::Warn,
                                format!(
                                    "Host memory is low ({} MB < 512 MB baseline)",
                                    total_mem_mb
                                ),
                                None,
                                Some("RS-0002".to_string()),
                                Some(
                                    "Provide at least 512 MB RAM for reliable operation."
                                        .to_string(),
                                ),
                            )
                        }
                    } else {
                        (
                            DiagnosticStatus::Pass,
                            "Host memory check passed".to_string(),
                            None,
                            None,
                            None,
                        )
                    }
                }
                #[cfg(not(unix))]
                {
                    (
                        DiagnosticStatus::Pass,
                        "Host memory check passed".to_string(),
                        None,
                        None,
                        None,
                    )
                }
            },
        )
        .await,
    );

    // 7. System OS & Architecture Supported
    checks.push(
        run_bounded_check(
            "system.os_arch_supported",
            "system",
            check_timeout,
            || async {
                let classification = PlatformClassifier::evaluate_host();
                let os = std::env::consts::OS;
                let arch = std::env::consts::ARCH;
                match classification.overall_tier {
                    ClassificationTier::Supported => (
                        DiagnosticStatus::Pass,
                        format!("Platform {} / {} is fully supported", os, arch),
                        None,
                        None,
                        None,
                    ),
                    ClassificationTier::CompatibleUnverified => (
                        DiagnosticStatus::Warn,
                        format!("Platform {} / {} is compatible but unverified", os, arch),
                        None,
                        Some(format!("{RS_3025}")),
                        Some(
                            "Review docs/platforms.md for qualified deployment targets."
                                .to_string(),
                        ),
                    ),
                    ClassificationTier::Unsupported => (
                        DiagnosticStatus::Fail,
                        format!("Platform {} / {} is unsupported", os, arch),
                        None,
                        Some(format!("{RS_3028}")),
                        Some(
                            "RockStream requires 64-bit Linux (x86_64/aarch64) or macOS."
                                .to_string(),
                        ),
                    ),
                }
            },
        )
        .await,
    );

    // 7b. Platform Classification Details
    checks.push(
        run_bounded_check(
            "platform.classification",
            "platform",
            check_timeout,
            || async {
                let classification = PlatformClassifier::evaluate_host();
                let os = std::env::consts::OS;
                let arch = std::env::consts::ARCH;
                match classification.overall_tier {
                    ClassificationTier::Supported => (
                        DiagnosticStatus::Pass,
                        format!("Host environment [{}/{}] tier: Supported", os, arch),
                        Some(format!(
                            "Arch: {} (tier: {}), OS: {} (tier: {}), Libc: {} (tier: {})",
                            classification.architecture.name,
                            classification.architecture.tier,
                            classification.operating_system.name,
                            classification.operating_system.tier,
                            classification.libc_runtime.name,
                            classification.libc_runtime.tier
                        )),
                        None,
                        None,
                    ),
                    ClassificationTier::CompatibleUnverified => (
                        DiagnosticStatus::Warn,
                        format!(
                            "Host environment [{}/{}] tier: Compatible, unverified",
                            os, arch
                        ),
                        Some(classification.warnings.join("; ")),
                        Some(format!("{RS_3025}")),
                        Some(
                            "Check contracts/platform-matrix.toml for qualified release profiles."
                                .to_string(),
                        ),
                    ),
                    ClassificationTier::Unsupported => (
                        DiagnosticStatus::Fail,
                        format!("Host environment [{}/{}] tier: Unsupported", os, arch),
                        Some(
                            "Host fails minimum platform prerequisites for 64-bit execution"
                                .to_string(),
                        ),
                        Some(format!("{RS_3028}")),
                        Some("Migrate to a supported Linux/macOS 64-bit environment.".to_string()),
                    ),
                }
            },
        )
        .await,
    );

    // 7c. Platform Libc Compatibility Check
    checks.push(
        run_bounded_check(
            "platform.libc_compatibility",
            "platform",
            check_timeout,
            || async {
                let libc_eval = PlatformClassifier::evaluate_libc();
                match libc_eval.tier {
                    ClassificationTier::Supported => (
                        DiagnosticStatus::Pass,
                        format!(
                            "C library runtime {} is supported ({})",
                            libc_eval.name,
                            libc_eval.version.as_deref().unwrap_or("standard")
                        ),
                        None,
                        None,
                        None,
                    ),
                    ClassificationTier::CompatibleUnverified => (
                        DiagnosticStatus::Warn,
                        format!("C library runtime {} is unverified", libc_eval.name),
                        libc_eval.reason,
                        Some(format!("{RS_3025}")),
                        Some("Verify glibc >= 2.31 or musl >= 1.2.3 compatibility.".to_string()),
                    ),
                    ClassificationTier::Unsupported => (
                        DiagnosticStatus::Fail,
                        format!("C library runtime {} is unsupported", libc_eval.name),
                        libc_eval.reason,
                        Some(format!("{RS_3028}")),
                        Some("Upgrade host C library or deploy via Debian 12 / Ubuntu 24.04 container.".to_string()),
                    ),
                }
            },
        )
        .await,
    );

    // 7d. Platform Container Security Profile Check
    checks.push(
        run_bounded_check(
            "platform.container_security",
            "platform",
            check_timeout,
            || async {
                let is_container = Path::new("/.dockerenv").exists()
                    || Path::new("/run/.containerenv").exists()
                    || std::env::var("ROCKSTREAM_CONTAINER").is_ok()
                    || std::env::var("container").is_ok();

                if !is_container {
                    (
                        DiagnosticStatus::Pass,
                        "Non-container native host execution".to_string(),
                        None,
                        None,
                        None,
                    )
                } else {
                    #[cfg(unix)]
                    let uid = unsafe { libc::getuid() };
                    #[cfg(not(unix))]
                    let uid = 10001;

                    if uid == 0 {
                        (
                            DiagnosticStatus::Warn,
                            "Container is executing as root (UID 0)".to_string(),
                            Some("Production containers must run unprivileged as user rockstream (UID 10001)".to_string()),
                            Some(format!("{RS_3026}")),
                            Some("Set 'USER rockstream:rockstream' or 'runAsUser: 10001' in container securityContext.".to_string()),
                        )
                    } else {
                        (
                            DiagnosticStatus::Pass,
                            format!("Container executing securely as non-root user (UID {uid})"),
                            Some("Complies with Kubernetes restricted Pod Security Standard".to_string()),
                            None,
                            None,
                        )
                    }
                }
            },
        )
        .await,
    );

    // 7e. Platform Port Availability Check
    checks.push(
        run_bounded_check(
            "platform.port_availability",
            "platform",
            check_timeout,
            || async {
                let standard_ports = [
                    (5432, "PGWire SQL"),
                    (9090, "Management / Metrics"),
                    (9100, "Worker DataPlane RPC"),
                    (9200, "Control Raft RPC"),
                ];
                let mut conflicts = Vec::new();
                for (port, name) in &standard_ports {
                    // Try to bind ephemeral test listener
                    match std::net::TcpListener::bind(("127.0.0.1", *port)) {
                        Ok(listener) => {
                            drop(listener);
                        }
                        Err(e) if e.kind() == std::io::ErrorKind::AddrInUse => {
                            conflicts.push(format!("Port {port} ({name}) is in use"));
                        }
                        Err(_) => {
                            // Permission or other transient network restriction; ignore
                        }
                    }
                }
                if conflicts.is_empty() {
                    (
                        DiagnosticStatus::Pass,
                        "Standard listener ports (5432, 9090, 9100, 9200) are available".to_string(),
                        None,
                        None,
                        None,
                    )
                } else {
                    (
                        DiagnosticStatus::Warn,
                        format!("Port binding notice: {}", conflicts.join(", ")),
                        Some("Another process is currently listening on one or more standard ports".to_string()),
                        Some(format!("{RS_3027}")),
                        Some("Specify alternate listen ports via CLI options (--listen, --metrics-addr, etc.) if running alongside existing services.".to_string()),
                    )
                }
            },
        )
        .await,
    );

    // 8. Storage Checks (if configured)
    if let Some(ref storage_str) = opts.storage {
        // storage.path_or_url_valid
        checks.push(
            run_bounded_check(
                "storage.path_or_url_valid",
                "storage",
                check_timeout,
                || async {
                    let redacted = redact_secrets(storage_str);
                    if let Some(rest) = storage_str.strip_prefix("s3://") {
                        if rest.is_empty() || rest.starts_with('/') {
                            (
                                DiagnosticStatus::Fail,
                                format!("Invalid S3 storage URL format: {redacted}"),
                                None,
                                Some("RS-0002".to_string()),
                                Some("Use syntax s3://bucket-name/optional-prefix.".to_string()),
                            )
                        } else {
                            (
                                DiagnosticStatus::Pass,
                                format!("Storage URL syntax is valid ({redacted})"),
                                None,
                                None,
                                None,
                            )
                        }
                    } else {
                        (
                            DiagnosticStatus::Pass,
                            format!("Local storage path format is valid ({redacted})"),
                            None,
                            None,
                            None,
                        )
                    }
                },
            )
            .await,
        );

        // storage.readable_and_writable
        checks.push(
            run_bounded_check(
                "storage.readable_and_writable",
                "storage",
                check_timeout,
                || async {
                    if storage_str.starts_with("s3://") {
                        (
                            DiagnosticStatus::Pass,
                            "Remote object-store storage URL configured".to_string(),
                            None,
                            None,
                            None,
                        )
                    } else {
                        let path = PathBuf::from(storage_str);
                        if let Err(e) = std::fs::create_dir_all(&path) {
                            return (
                                DiagnosticStatus::Fail,
                                format!("Cannot create storage directory {}: {e}", path.display()),
                                None,
                                Some("RS-0003".to_string()),
                                Some("Verify storage directory path and permissions.".to_string()),
                            );
                        }
                        let test_file = path.join(".doctor_probe");
                        if let Err(e) = std::fs::write(&test_file, b"test") {
                            return (
                                DiagnosticStatus::Fail,
                                format!(
                                    "Storage directory {} is not writable: {e}",
                                    path.display()
                                ),
                                None,
                                Some("RS-0003".to_string()),
                                Some("Check storage directory write permissions.".to_string()),
                            );
                        }
                        let _ = std::fs::remove_file(&test_file);
                        (
                            DiagnosticStatus::Pass,
                            format!(
                                "Storage directory {} is readable and writable",
                                path.display()
                            ),
                            None,
                            None,
                            None,
                        )
                    }
                },
            )
            .await,
        );

        // storage.deep_roundtrip
        if opts.deep {
            checks.push(run_bounded_check("storage.deep_roundtrip", "storage", check_timeout, || async {
                let probe_uuid = uuid::Uuid::new_v4();
                if storage_str.starts_with("s3://") {
                    (
                        DiagnosticStatus::Pass,
                        "Deep probe for S3 skipped in local doctor mode".to_string(),
                        None,
                        None,
                        None,
                    )
                } else {
                    let probe_dir = PathBuf::from(storage_str).join("_rockstream_doctor").join(probe_uuid.to_string());
                    if let Err(e) = std::fs::create_dir_all(&probe_dir) {
                        return (
                            DiagnosticStatus::Fail,
                            format!("Deep probe directory creation failed: {e}"),
                            None,
                            Some("RS-0003".to_string()),
                            Some("Check storage path accessibility.".to_string()),
                        );
                    }
                    let probe_file = probe_dir.join("probe");
                    let test_payload = b"rockstream_doctor_deep_roundtrip_payload_v1";
                    if let Err(e) = std::fs::write(&probe_file, test_payload) {
                        let _ = std::fs::remove_dir_all(&probe_dir);
                        return (
                            DiagnosticStatus::Fail,
                            format!("Deep probe write failed: {e}"),
                            None,
                            Some("RS-0003".to_string()),
                            Some("Check storage write permissions.".to_string()),
                        );
                    }
                    match std::fs::read(&probe_file) {
                        Ok(data) => {
                            let _ = std::fs::remove_file(&probe_file);
                            let _ = std::fs::remove_dir_all(probe_dir.parent().unwrap_or(&probe_dir));
                            if data == test_payload {
                                (
                                    DiagnosticStatus::Pass,
                                    "Deep probe write, read, digest-verification, and cleanup succeeded".to_string(),
                                    None,
                                    None,
                                    None,
                                )
                            } else {
                                (
                                    DiagnosticStatus::Fail,
                                    "Deep probe digest mismatch on storage read".to_string(),
                                    None,
                                    Some("RS-0003".to_string()),
                                    Some("Check storage device integrity.".to_string()),
                                )
                            }
                        }
                        Err(e) => {
                            let _ = std::fs::remove_dir_all(&probe_dir);
                            (
                                DiagnosticStatus::Fail,
                                format!("Deep probe read failed: {e}"),
                                None,
                                Some("RS-0003".to_string()),
                                Some("Check storage read permissions.".to_string()),
                            )
                        }
                    }
                }
            }).await);
        }

        // platform.storage_filesystem
        checks.push(
            run_bounded_check(
                "platform.storage_filesystem",
                "platform",
                check_timeout,
                || async {
                    let eval = PlatformClassifier::evaluate_storage_backend(storage_str);
                    match eval.tier {
                        ClassificationTier::Supported => (
                            DiagnosticStatus::Pass,
                            format!("Storage backend {} is supported ({})", eval.name, eval.version.as_deref().unwrap_or("standard")),
                            eval.reason,
                            None,
                            None,
                        ),
                        ClassificationTier::CompatibleUnverified => (
                            DiagnosticStatus::Warn,
                            format!("Storage backend {} is compatible but unverified", eval.name),
                            eval.reason,
                            Some(format!("{RS_3025}")),
                            Some("Review contracts/platform-matrix.toml for qualified storage backends.".to_string()),
                        ),
                        ClassificationTier::Unsupported => (
                            DiagnosticStatus::Fail,
                            format!("Storage backend {} is unsupported", eval.name),
                            eval.reason,
                            Some(format!("{RS_3028}")),
                            Some("Use local NVMe/SSD filesystem (LFS) or AWS S3 / MinIO object store.".to_string()),
                        ),
                    }
                },
            )
            .await,
        );

        // platform.backend_compatibility
        checks.push(
            run_bounded_check(
                "platform.backend_compatibility",
                "platform",
                check_timeout,
                || async {
                    let eval = PlatformClassifier::evaluate_storage_backend(storage_str);
                    (
                        DiagnosticStatus::Pass,
                        format!("External backend tier: {} [{}]", eval.tier, eval.name),
                        eval.reason,
                        None,
                        None,
                    )
                },
            )
            .await,
        );
    }

    // 9. Control Reachability Check (if configured)
    if let Some(ref control_url) = opts.control {
        checks.push(run_bounded_check("control.tcp_connect_and_status", "control", check_timeout, || async {
            let addr_str = control_url.trim_start_matches("http://").trim_start_matches("https://");
            match tokio::net::TcpStream::connect(addr_str).await {
                Ok(_) => (
                    DiagnosticStatus::Pass,
                    format!("Connected to control endpoint at {}", control_url),
                    None,
                    None,
                    None,
                ),
                Err(e) => (
                    DiagnosticStatus::Fail,
                    format!("Cannot connect to control endpoint {}: {e}", control_url),
                    None,
                    Some("RS-0003".to_string()),
                    Some("Verify the control service is running and accessible at this address.".to_string()),
                ),
            }
        }).await);
    }

    // 10. Gateway Reachability Check (if configured)
    if let Some(ref gateway_addr) = opts.gateway {
        checks.push(
            run_bounded_check(
                "gateway.tcp_connect_and_version",
                "gateway",
                check_timeout,
                || async {
                    match tokio::net::TcpStream::connect(gateway_addr).await {
                        Ok(_) => (
                            DiagnosticStatus::Pass,
                            format!("Connected to gateway pgwire endpoint at {}", gateway_addr),
                            None,
                            None,
                            None,
                        ),
                        Err(e) => (
                            DiagnosticStatus::Fail,
                            format!(
                                "Cannot connect to gateway pgwire endpoint {}: {e}",
                                gateway_addr
                            ),
                            None,
                            Some("RS-0003".to_string()),
                            Some(
                                "Verify the gateway is running and listening on this port."
                                    .to_string(),
                            ),
                        ),
                    }
                },
            )
            .await,
        );
    }

    // 11. TLS Material Check (if configured)
    let tls_configured = opts.tls_cert_path.is_some()
        || opts.tls_key_path.is_some()
        || opts.internal_tls_cert_path.is_some()
        || opts.internal_tls_key_path.is_some();
    if tls_configured {
        checks.push(
            run_bounded_check(
                "tls.gateway_and_internal_material",
                "tls",
                check_timeout,
                || async {
                    let mut errors = Vec::new();
                    if let Some(ref cert) = opts.tls_cert_path {
                        if !cert.exists() {
                            errors.push(format!(
                                "Gateway TLS certificate not found: {}",
                                cert.display()
                            ));
                        }
                    }
                    if let Some(ref key) = opts.tls_key_path {
                        if !key.exists() {
                            errors.push(format!("Gateway TLS key not found: {}", key.display()));
                        }
                    }
                    if let Some(ref cert) = opts.internal_tls_cert_path {
                        if !cert.exists() {
                            errors.push(format!(
                                "Internal TLS certificate not found: {}",
                                cert.display()
                            ));
                        }
                    }
                    if let Some(ref key) = opts.internal_tls_key_path {
                        if !key.exists() {
                            errors.push(format!("Internal TLS key not found: {}", key.display()));
                        }
                    }
                    if errors.is_empty() {
                        (
                            DiagnosticStatus::Pass,
                            "Configured TLS certificate and key files exist and are accessible"
                                .to_string(),
                            None,
                            None,
                            None,
                        )
                    } else {
                        (
                            DiagnosticStatus::Fail,
                            "TLS certificate/key material verification failed".to_string(),
                            Some(errors.join("; ")),
                            Some("RS-0002".to_string()),
                            Some("Verify TLS file paths and permissions.".to_string()),
                        )
                    }
                },
            )
            .await,
        );
    }

    // 12. Docker Daemon Check
    if opts.include_docker {
        checks.push(run_bounded_check("docker.daemon_available", "docker", check_timeout, || async {
            let docker_sock = Path::new("/var/run/docker.sock");
            if docker_sock.exists() {
                (
                    DiagnosticStatus::Pass,
                    "Docker daemon socket /var/run/docker.sock is available".to_string(),
                    None,
                    None,
                    None,
                )
            } else if std::env::var("DOCKER_HOST").is_ok() {
                (
                    DiagnosticStatus::Pass,
                    format!("DOCKER_HOST environment variable configured ({})", std::env::var("DOCKER_HOST").unwrap()),
                    None,
                    None,
                    None,
                )
            } else {
                (
                    DiagnosticStatus::Warn,
                    "Docker daemon socket /var/run/docker.sock not found".to_string(),
                    None,
                    Some("RS-0002".to_string()),
                    Some("Ensure Docker is running if running containerized qualification tests.".to_string()),
                )
            }
        }).await);
    } else {
        checks.push(DiagnosticCheckResult {
            id: "docker.daemon_available".to_string(),
            category: "docker".to_string(),
            status: DiagnosticStatus::Skip,
            summary: "Docker check skipped (pass --include-docker to probe)".to_string(),
            details: None,
            code: None,
            next_steps: None,
            duration_ms: 0,
        });
    }

    // Tally counts
    let mut passed_count = 0;
    let mut warn_count = 0;
    let mut failed_count = 0;
    let mut skipped_count = 0;

    for c in &checks {
        match c.status {
            DiagnosticStatus::Pass => passed_count += 1,
            DiagnosticStatus::Warn => warn_count += 1,
            DiagnosticStatus::Fail => failed_count += 1,
            DiagnosticStatus::Skip => skipped_count += 1,
        }
    }

    let overall_status = if failed_count > 0 {
        DiagnosticStatus::Fail
    } else if warn_count > 0 {
        DiagnosticStatus::Warn
    } else {
        DiagnosticStatus::Pass
    };

    let total_duration_ms = start_all.elapsed().as_millis() as u64;

    DoctorReport {
        status: overall_status,
        checks,
        passed_count,
        warn_count,
        failed_count,
        skipped_count,
        total_duration_ms,
    }
}

async fn run_bounded_check<F, Fut>(
    id: &str,
    category: &str,
    timeout: Duration,
    f: F,
) -> DiagnosticCheckResult
where
    F: FnOnce() -> Fut,
    Fut: std::future::Future<
        Output = (
            DiagnosticStatus,
            String,
            Option<String>,
            Option<String>,
            Option<String>,
        ),
    >,
{
    let start = Instant::now();
    match tokio::time::timeout(timeout, f()).await {
        Ok((status, summary, details, code, next_steps)) => DiagnosticCheckResult {
            id: id.to_string(),
            category: category.to_string(),
            status,
            summary: redact_secrets(&summary),
            details: details.map(|d| redact_secrets(&d)),
            code,
            next_steps,
            duration_ms: start.elapsed().as_millis() as u64,
        },
        Err(_) => DiagnosticCheckResult {
            id: id.to_string(),
            category: category.to_string(),
            status: DiagnosticStatus::Fail,
            summary: format!("Check timed out after {}s", timeout.as_secs()),
            details: None,
            code: Some("RS-0003".to_string()),
            next_steps: Some(
                "Check system responsiveness or endpoint network connectivity.".to_string(),
            ),
            duration_ms: start.elapsed().as_millis() as u64,
        },
    }
}

/// Async entry point for `rockstream doctor`.
pub async fn run_doctor_async(
    format: OutputFormat,
    opts: &DoctorOptions,
) -> Result<String, CliError> {
    let report = run_doctor_checks(opts).await;
    let rendered = render_output(&report, format);

    if report.status == DiagnosticStatus::Fail {
        return Err(CliError::new(
            RS_0003,
            format!(
                "doctor detected {} diagnostic failure(s)",
                report.failed_count
            ),
            rendered,
        ));
    }

    Ok(rendered)
}

/// Synchronous entry point for `rockstream doctor`.
pub fn run_doctor(format: OutputFormat, opts: &DoctorOptions) -> Result<String, CliError> {
    if tokio::runtime::Handle::try_current().is_ok() {
        let opts = opts.clone();
        std::thread::spawn(move || {
            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .map_err(|e| {
                    CliError::new(RS_0003, format!("failed to start tokio runtime: {e}"), "")
                })?;
            rt.block_on(run_doctor_async(format, &opts))
        })
        .join()
        .map_err(|_| CliError::new(RS_0003, "diagnostic runner thread panicked", ""))?
    } else {
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .map_err(|e| {
                CliError::new(RS_0003, format!("failed to start tokio runtime: {e}"), "")
            })?;
        rt.block_on(run_doctor_async(format, opts))
    }
}

#[cfg(unix)]
mod sys_ffi {
    #[repr(C)]
    pub struct rlimit {
        pub rlim_cur: u64,
        pub rlim_max: u64,
    }
    extern "C" {
        pub fn getrlimit(resource: std::os::raw::c_int, rlim: *mut rlimit) -> std::os::raw::c_int;
        pub fn sysconf(name: std::os::raw::c_int) -> std::os::raw::c_long;
    }
    pub const RLIMIT_NOFILE: std::os::raw::c_int = if cfg!(target_os = "macos") { 8 } else { 7 };
    pub const _SC_PHYS_PAGES: std::os::raw::c_int =
        if cfg!(target_os = "macos") { 200 } else { 85 };
    pub const _SC_PAGE_SIZE: std::os::raw::c_int = if cfg!(target_os = "macos") { 29 } else { 30 };
}
