[package]
name = "rockstream-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Query gateway service for RockStream (pgwire, HTTP)"

[dependencies]
rockstream-types = { workspace = true }
rockstream-storage = { workspace = true }
object_store = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
