//! SQL and UDF Function surface contributor (DOC-001).

use crate::manifest::{FunctionDescriptor, FunctionSurface};

pub struct FunctionContributor;

impl FunctionContributor {
    /// Extract built-in scalar, aggregate, and window functions from `rockstream-sql` and `rockstream-ops`.
    pub fn extract() -> FunctionSurface {
        let mut functions = vec![
            // Scalar functions
            FunctionDescriptor {
                name: "abs".to_string(),
                category: "scalar".to_string(),
                signature: "abs(int8) -> int8".to_string(),
                argument_types: vec!["INT8".to_string()],
                return_type: "INT8".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Returns the absolute value of an integer expression".to_string(),
                examples: vec!["SELECT abs(-42);".to_string()],
            },
            FunctionDescriptor {
                name: "cast_int64".to_string(),
                category: "scalar".to_string(),
                signature: "cast_int64(any) -> int8".to_string(),
                argument_types: vec!["ANY".to_string()],
                return_type: "INT8".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Casts input expression to 64-bit signed integer".to_string(),
                examples: vec!["SELECT cast_int64('123');".to_string()],
            },
            FunctionDescriptor {
                name: "char_length".to_string(),
                category: "scalar".to_string(),
                signature: "char_length(text) -> int8".to_string(),
                argument_types: vec!["TEXT".to_string()],
                return_type: "INT8".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Computes character count of text".to_string(),
                examples: vec!["SELECT char_length('rockstream');".to_string()],
            },
            FunctionDescriptor {
                name: "character_length".to_string(),
                category: "scalar".to_string(),
                signature: "character_length(text) -> int8".to_string(),
                argument_types: vec!["TEXT".to_string()],
                return_type: "INT8".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Computes character count of text".to_string(),
                examples: vec!["SELECT character_length('rockstream');".to_string()],
            },
            FunctionDescriptor {
                name: "coalesce".to_string(),
                category: "scalar".to_string(),
                signature: "coalesce(any, ...) -> any".to_string(),
                argument_types: vec!["ANY".to_string(), "ANY".to_string()],
                return_type: "ANY".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Returns the first non-null argument".to_string(),
                examples: vec!["SELECT coalesce(NULL, 'fallback');".to_string()],
            },
            FunctionDescriptor {
                name: "concat".to_string(),
                category: "scalar".to_string(),
                signature: "concat(text, ...) -> text".to_string(),
                argument_types: vec!["TEXT".to_string(), "TEXT".to_string()],
                return_type: "TEXT".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Concatenates string arguments".to_string(),
                examples: vec!["SELECT concat('hello', ' ', 'world');".to_string()],
            },
            FunctionDescriptor {
                name: "current_date".to_string(),
                category: "scalar".to_string(),
                signature: "current_date() -> date".to_string(),
                argument_types: vec![],
                return_type: "DATE".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Returns current calendar date".to_string(),
                examples: vec!["SELECT current_date;".to_string()],
            },
            FunctionDescriptor {
                name: "current_timestamp".to_string(),
                category: "scalar".to_string(),
                signature: "current_timestamp() -> timestamptz".to_string(),
                argument_types: vec![],
                return_type: "TIMESTAMPTZ".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Returns current transaction timestamp with UTC zone".to_string(),
                examples: vec!["SELECT current_timestamp;".to_string()],
            },
            FunctionDescriptor {
                name: "date_trunc".to_string(),
                category: "scalar".to_string(),
                signature: "date_trunc(text, timestamp) -> timestamp".to_string(),
                argument_types: vec!["TEXT".to_string(), "TIMESTAMP".to_string()],
                return_type: "TIMESTAMP".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Truncates timestamp to specified date precision part".to_string(),
                examples: vec![
                    "SELECT date_trunc('hour', timestamp '2026-08-24 15:30:00');".to_string(),
                ],
            },
            FunctionDescriptor {
                name: "extract".to_string(),
                category: "scalar".to_string(),
                signature: "extract(text, timestamp) -> int8".to_string(),
                argument_types: vec!["TEXT".to_string(), "TIMESTAMP".to_string()],
                return_type: "INT8".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Extracts numeric subfield from date or timestamp".to_string(),
                examples: vec![
                    "SELECT extract('year', timestamp '2026-08-24 15:30:00');".to_string()
                ],
            },
            FunctionDescriptor {
                name: "greatest".to_string(),
                category: "scalar".to_string(),
                signature: "greatest(any, ...) -> any".to_string(),
                argument_types: vec!["ANY".to_string(), "ANY".to_string()],
                return_type: "ANY".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Selects greatest value from argument list".to_string(),
                examples: vec!["SELECT greatest(10, 20, 5);".to_string()],
            },
            FunctionDescriptor {
                name: "least".to_string(),
                category: "scalar".to_string(),
                signature: "least(any, ...) -> any".to_string(),
                argument_types: vec!["ANY".to_string(), "ANY".to_string()],
                return_type: "ANY".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Selects smallest value from argument list".to_string(),
                examples: vec!["SELECT least(10, 20, 5);".to_string()],
            },
            FunctionDescriptor {
                name: "length".to_string(),
                category: "scalar".to_string(),
                signature: "length(text) -> int8".to_string(),
                argument_types: vec!["TEXT".to_string()],
                return_type: "INT8".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Computes character length of string".to_string(),
                examples: vec!["SELECT length('rockstream');".to_string()],
            },
            FunctionDescriptor {
                name: "lower".to_string(),
                category: "scalar".to_string(),
                signature: "lower(text) -> text".to_string(),
                argument_types: vec!["TEXT".to_string()],
                return_type: "TEXT".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Converts text characters to lowercase".to_string(),
                examples: vec!["SELECT lower('ROCKSTREAM');".to_string()],
            },
            FunctionDescriptor {
                name: "ltrim".to_string(),
                category: "scalar".to_string(),
                signature: "ltrim(text) -> text".to_string(),
                argument_types: vec!["TEXT".to_string()],
                return_type: "TEXT".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Strips leading whitespace from string".to_string(),
                examples: vec!["SELECT ltrim('   hello');".to_string()],
            },
            FunctionDescriptor {
                name: "now".to_string(),
                category: "scalar".to_string(),
                signature: "now() -> timestamptz".to_string(),
                argument_types: vec![],
                return_type: "TIMESTAMPTZ".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Returns current transaction timestamp".to_string(),
                examples: vec!["SELECT now();".to_string()],
            },
            FunctionDescriptor {
                name: "nullif".to_string(),
                category: "scalar".to_string(),
                signature: "nullif(any, any) -> any".to_string(),
                argument_types: vec!["ANY".to_string(), "ANY".to_string()],
                return_type: "ANY".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Returns null if first argument equals second argument".to_string(),
                examples: vec!["SELECT nullif(10, 10);".to_string()],
            },
            FunctionDescriptor {
                name: "replace".to_string(),
                category: "scalar".to_string(),
                signature: "replace(text, text, text) -> text".to_string(),
                argument_types: vec!["TEXT".to_string(), "TEXT".to_string(), "TEXT".to_string()],
                return_type: "TEXT".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Replaces occurrences of substring in source string".to_string(),
                examples: vec!["SELECT replace('abc_def', '_', '-');".to_string()],
            },
            FunctionDescriptor {
                name: "rtrim".to_string(),
                category: "scalar".to_string(),
                signature: "rtrim(text) -> text".to_string(),
                argument_types: vec!["TEXT".to_string()],
                return_type: "TEXT".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Strips trailing whitespace from string".to_string(),
                examples: vec!["SELECT rtrim('hello   ');".to_string()],
            },
            FunctionDescriptor {
                name: "substr".to_string(),
                category: "scalar".to_string(),
                signature: "substr(text, int8, int8) -> text".to_string(),
                argument_types: vec!["TEXT".to_string(), "INT8".to_string(), "INT8".to_string()],
                return_type: "TEXT".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Extracts substring starting at 1-based index with optional length"
                    .to_string(),
                examples: vec!["SELECT substr('rockstream', 1, 4);".to_string()],
            },
            FunctionDescriptor {
                name: "substring".to_string(),
                category: "scalar".to_string(),
                signature: "substring(text, int8, int8) -> text".to_string(),
                argument_types: vec!["TEXT".to_string(), "INT8".to_string(), "INT8".to_string()],
                return_type: "TEXT".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Extracts substring starting at 1-based index with optional length"
                    .to_string(),
                examples: vec!["SELECT substring('rockstream' from 1 for 4);".to_string()],
            },
            FunctionDescriptor {
                name: "trim".to_string(),
                category: "scalar".to_string(),
                signature: "trim(text) -> text".to_string(),
                argument_types: vec!["TEXT".to_string()],
                return_type: "TEXT".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Removes leading and trailing whitespace".to_string(),
                examples: vec!["SELECT trim('   hello   ');".to_string()],
            },
            FunctionDescriptor {
                name: "upper".to_string(),
                category: "scalar".to_string(),
                signature: "upper(text) -> text".to_string(),
                argument_types: vec!["TEXT".to_string()],
                return_type: "TEXT".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Converts text characters to uppercase".to_string(),
                examples: vec!["SELECT upper('rockstream');".to_string()],
            },
            // Aggregate functions
            FunctionDescriptor {
                name: "array_agg".to_string(),
                category: "aggregate".to_string(),
                signature: "array_agg(any) -> array".to_string(),
                argument_types: vec!["ANY".to_string()],
                return_type: "ARRAY".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Aggregates grouped values into an array".to_string(),
                examples: vec!["SELECT array_agg(id) FROM t GROUP BY category;".to_string()],
            },
            FunctionDescriptor {
                name: "avg".to_string(),
                category: "aggregate".to_string(),
                signature: "avg(int8) -> float8".to_string(),
                argument_types: vec!["INT8".to_string()],
                return_type: "FLOAT8".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Computes arithmetic mean over non-null numeric values".to_string(),
                examples: vec!["SELECT avg(val) FROM t;".to_string()],
            },
            FunctionDescriptor {
                name: "bool_and".to_string(),
                category: "aggregate".to_string(),
                signature: "bool_and(boolean) -> boolean".to_string(),
                argument_types: vec!["BOOLEAN".to_string()],
                return_type: "BOOLEAN".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Returns true if all non-null input values are true, otherwise false"
                    .to_string(),
                examples: vec!["SELECT bool_and(flag) FROM t;".to_string()],
            },
            FunctionDescriptor {
                name: "bool_or".to_string(),
                category: "aggregate".to_string(),
                signature: "bool_or(boolean) -> boolean".to_string(),
                argument_types: vec!["BOOLEAN".to_string()],
                return_type: "BOOLEAN".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Returns true if any non-null input value is true, otherwise false"
                    .to_string(),
                examples: vec!["SELECT bool_or(flag) FROM t;".to_string()],
            },
            FunctionDescriptor {
                name: "count".to_string(),
                category: "aggregate".to_string(),
                signature: "count(*) -> int8".to_string(),
                argument_types: vec!["ANY".to_string()],
                return_type: "INT8".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Counts the number of input rows".to_string(),
                examples: vec!["SELECT count(*) FROM t;".to_string()],
            },
            FunctionDescriptor {
                name: "max".to_string(),
                category: "aggregate".to_string(),
                signature: "max(any) -> any".to_string(),
                argument_types: vec!["ANY".to_string()],
                return_type: "ANY".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Returns maximum value across grouped rows".to_string(),
                examples: vec!["SELECT max(score) FROM t;".to_string()],
            },
            FunctionDescriptor {
                name: "min".to_string(),
                category: "aggregate".to_string(),
                signature: "min(any) -> any".to_string(),
                argument_types: vec!["ANY".to_string()],
                return_type: "ANY".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Returns minimum value across grouped rows".to_string(),
                examples: vec!["SELECT min(score) FROM t;".to_string()],
            },
            FunctionDescriptor {
                name: "sum".to_string(),
                category: "aggregate".to_string(),
                signature: "sum(int8) -> int8".to_string(),
                argument_types: vec!["INT8".to_string()],
                return_type: "INT8".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Computes sum of 64-bit integer values".to_string(),
                examples: vec!["SELECT sum(amount) FROM t;".to_string()],
            },
            FunctionDescriptor {
                name: "sum".to_string(),
                category: "aggregate".to_string(),
                signature: "sum(numeric) -> numeric".to_string(),
                argument_types: vec!["NUMERIC".to_string()],
                return_type: "NUMERIC".to_string(),
                null_handling: "returns_null_on_null".to_string(),
                description: "Computes sum of arbitrary-precision numeric values".to_string(),
                examples: vec!["SELECT sum(price) FROM t;".to_string()],
            },
            // Window functions
            FunctionDescriptor {
                name: "dense_rank".to_string(),
                category: "window".to_string(),
                signature: "dense_rank() -> int8".to_string(),
                argument_types: vec![],
                return_type: "INT8".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Computes rank without gaps across peer groups".to_string(),
                examples: vec![
                    "SELECT dense_rank() OVER (PARTITION BY dep ORDER BY sal DESC);".to_string(),
                ],
            },
            FunctionDescriptor {
                name: "lag".to_string(),
                category: "window".to_string(),
                signature: "lag(any, int8) -> any".to_string(),
                argument_types: vec!["ANY".to_string(), "INT8".to_string()],
                return_type: "ANY".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Accesses value from prior row within current window partition"
                    .to_string(),
                examples: vec!["SELECT lag(price, 1) OVER (ORDER BY ts);".to_string()],
            },
            FunctionDescriptor {
                name: "lead".to_string(),
                category: "window".to_string(),
                signature: "lead(any, int8) -> any".to_string(),
                argument_types: vec!["ANY".to_string(), "INT8".to_string()],
                return_type: "ANY".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Accesses value from subsequent row within current window partition"
                    .to_string(),
                examples: vec!["SELECT lead(price, 1) OVER (ORDER BY ts);".to_string()],
            },
            FunctionDescriptor {
                name: "rank".to_string(),
                category: "window".to_string(),
                signature: "rank() -> int8".to_string(),
                argument_types: vec![],
                return_type: "INT8".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Computes rank with gaps across peer groups".to_string(),
                examples: vec![
                    "SELECT rank() OVER (PARTITION BY dep ORDER BY sal DESC);".to_string()
                ],
            },
            FunctionDescriptor {
                name: "row_number".to_string(),
                category: "window".to_string(),
                signature: "row_number() -> int8".to_string(),
                argument_types: vec![],
                return_type: "INT8".to_string(),
                null_handling: "handles_null".to_string(),
                description: "Returns sequential 1-based index within current window partition"
                    .to_string(),
                examples: vec![
                    "SELECT row_number() OVER (PARTITION BY dep ORDER BY id);".to_string()
                ],
            },
        ];

        functions.sort_by(|a, b| {
            (a.name.as_str(), a.signature.as_str()).cmp(&(b.name.as_str(), b.signature.as_str()))
        });
        FunctionSurface { functions }
    }
}
