[package]
name = "rockstream-plan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "PlanNode IR and physical OpNode graph for RockStream"

[dependencies]
rockstream-types = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
